language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
    - cram test-cram/
    - py.test croncoat/test

#whitelist only certain branches
branches:
    only:
        - master
        - develop

